--
-- PostgreSQL database dump
--

-- Dumped from database version 17.8 (9c8634e)
-- Dumped by pg_dump version 18.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: delete_old_tavily_records(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.delete_old_tavily_records() RETURNS integer
    LANGUAGE plpgsql
    AS $$

DECLARE

    rows_deleted int;

BEGIN

    DELETE FROM "Tavily"

    WHERE created_at < NOW() - INTERVAL '1 month';

    GET DIAGNOSTICS rows_deleted = ROW_COUNT;



    RETURN rows_deleted;

END;

$$;


--
-- Name: delete_oldest_tavily_record(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.delete_oldest_tavily_record() RETURNS integer
    LANGUAGE plpgsql
    AS $$

DECLARE

    rows_deleted int;

BEGIN

    DELETE FROM "Tavily"

    WHERE id = ( -- ※ 'id' はあなたのテーブルの主キーにしてください

        SELECT id

        FROM "Tavily"

        ORDER BY created_at ASC

        LIMIT 1

    );



    GET DIAGNOSTICS rows_deleted = ROW_COUNT;

    RETURN rows_deleted;

END;

$$;


--
-- Name: delete_oldest_tavily_records(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.delete_oldest_tavily_records() RETURNS integer
    LANGUAGE plpgsql
    AS $$DECLARE

    rows_deleted int;

BEGIN

    DELETE FROM "Tavily"

    WHERE id = (

        SELECT id

        FROM "Tavily"

        ORDER BY created_at ASC

        LIMIT 1

    );



    GET DIAGNOSTICS rows_deleted = ROW_COUNT;



    RETURN rows_deleted;

END;$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Category; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Category" (
    id integer NOT NULL,
    name character varying NOT NULL,
    is_team boolean DEFAULT false NOT NULL
);


--
-- Name: TABLE "Category"; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public."Category" IS '部門';


--
-- Name: Category_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Category" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Category_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Country; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Country" (
    iso_code integer NOT NULL,
    latitude numeric DEFAULT '0'::numeric NOT NULL,
    longitude numeric DEFAULT '0'::numeric NOT NULL,
    names jsonb NOT NULL,
    en_name text,
    ja_name text,
    iso_alpha2 text,
    CONSTRAINT "Country_iso_alpha2_check" CHECK ((length(iso_alpha2) <= 2))
);


--
-- Name: TABLE "Country"; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public."Country" IS '各国の基本情報';


--
-- Name: Participant; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Participant" (
    id integer NOT NULL,
    name character varying NOT NULL,
    year integer NOT NULL,
    iso_code integer NOT NULL,
    is_cancelled boolean DEFAULT false NOT NULL,
    category integer NOT NULL,
    ticket_class character varying NOT NULL
);


--
-- Name: TABLE "Participant"; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public."Participant" IS '出場者（チーム単位）';


--
-- Name: ParticipantMember; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."ParticipantMember" (
    id bigint NOT NULL,
    participant integer NOT NULL,
    name character varying NOT NULL,
    iso_code integer NOT NULL
);


--
-- Name: TABLE "ParticipantMember"; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public."ParticipantMember" IS 'チームの個別メンバー';


--
-- Name: ParticipantMember_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."ParticipantMember" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ParticipantMember_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Participant_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Participant" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Participant_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: RankingResult; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."RankingResult" (
    id bigint NOT NULL,
    year integer NOT NULL,
    category integer NOT NULL,
    round character varying,
    participant integer NOT NULL,
    rank integer NOT NULL
);


--
-- Name: TABLE "RankingResult"; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public."RankingResult" IS 'ランキング形式部門の結果';


--
-- Name: RankingResult_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."RankingResult" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."RankingResult_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Tavily; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Tavily" (
    id integer NOT NULL,
    cache_key text NOT NULL,
    search_results jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    answer_translation jsonb DEFAULT '{}'::jsonb NOT NULL
);


--
-- Name: Tavily_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Tavily" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Tavily_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: TournamentResult; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."TournamentResult" (
    id integer NOT NULL,
    year integer NOT NULL,
    category integer NOT NULL,
    round character varying NOT NULL,
    winner integer NOT NULL,
    loser integer NOT NULL
);


--
-- Name: TABLE "TournamentResult"; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public."TournamentResult" IS 'トーナメントの結果';


--
-- Name: TournamentResult_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."TournamentResult" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."TournamentResult_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Year; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Year" (
    year integer NOT NULL,
    starts_at timestamp with time zone,
    ends_at timestamp with time zone,
    categories integer[],
    city text,
    iso_code integer
);


--
-- Name: TABLE "Year"; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public."Year" IS '年度と開催日';


--
-- Name: Category Category_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Category"
    ADD CONSTRAINT "Category_name_key" UNIQUE (name);


--
-- Name: Category Category_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Category"
    ADD CONSTRAINT "Category_pkey" PRIMARY KEY (id);


--
-- Name: Country Country_iso_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Country"
    ADD CONSTRAINT "Country_iso_code_key" UNIQUE (iso_code);


--
-- Name: Country Country_names_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Country"
    ADD CONSTRAINT "Country_names_key" UNIQUE (names);


--
-- Name: Country Country_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Country"
    ADD CONSTRAINT "Country_pkey" PRIMARY KEY (iso_code);


--
-- Name: ParticipantMember ParticipantMember_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ParticipantMember"
    ADD CONSTRAINT "ParticipantMember_pkey" PRIMARY KEY (id);


--
-- Name: Participant Participant_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Participant"
    ADD CONSTRAINT "Participant_pkey" PRIMARY KEY (id);


--
-- Name: RankingResult RankingResult_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."RankingResult"
    ADD CONSTRAINT "RankingResult_pkey" PRIMARY KEY (id);


--
-- Name: Tavily Tavily_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Tavily"
    ADD CONSTRAINT "Tavily_name_key" UNIQUE (cache_key);


--
-- Name: Tavily Tavily_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Tavily"
    ADD CONSTRAINT "Tavily_pkey" PRIMARY KEY (id);


--
-- Name: TournamentResult TournamentResult_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."TournamentResult"
    ADD CONSTRAINT "TournamentResult_pkey" PRIMARY KEY (id);


--
-- Name: Year Year_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Year"
    ADD CONSTRAINT "Year_pkey" PRIMARY KEY (year);


--
-- Name: Year Year_year_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Year"
    ADD CONSTRAINT "Year_year_key" UNIQUE (year);


--
-- Name: ParticipantMember ParticipantMember_iso_code_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ParticipantMember"
    ADD CONSTRAINT "ParticipantMember_iso_code_fkey" FOREIGN KEY (iso_code) REFERENCES public."Country"(iso_code) ON DELETE CASCADE;


--
-- Name: ParticipantMember ParticipantMember_participant_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ParticipantMember"
    ADD CONSTRAINT "ParticipantMember_participant_fkey" FOREIGN KEY (participant) REFERENCES public."Participant"(id) ON DELETE CASCADE;


--
-- Name: Participant Participant_category_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Participant"
    ADD CONSTRAINT "Participant_category_fkey" FOREIGN KEY (category) REFERENCES public."Category"(id) ON DELETE CASCADE;


--
-- Name: Participant Participant_iso_code_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Participant"
    ADD CONSTRAINT "Participant_iso_code_fkey" FOREIGN KEY (iso_code) REFERENCES public."Country"(iso_code) ON DELETE CASCADE;


--
-- Name: Participant Participant_year_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Participant"
    ADD CONSTRAINT "Participant_year_fkey" FOREIGN KEY (year) REFERENCES public."Year"(year) ON DELETE CASCADE;


--
-- Name: RankingResult RankingResult_category_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."RankingResult"
    ADD CONSTRAINT "RankingResult_category_fkey" FOREIGN KEY (category) REFERENCES public."Category"(id) ON DELETE CASCADE;


--
-- Name: RankingResult RankingResult_participant_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."RankingResult"
    ADD CONSTRAINT "RankingResult_participant_fkey" FOREIGN KEY (participant) REFERENCES public."Participant"(id) ON DELETE CASCADE;


--
-- Name: RankingResult RankingResult_year_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."RankingResult"
    ADD CONSTRAINT "RankingResult_year_fkey" FOREIGN KEY (year) REFERENCES public."Year"(year) ON DELETE CASCADE;


--
-- Name: TournamentResult TournamentResult_category_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."TournamentResult"
    ADD CONSTRAINT "TournamentResult_category_fkey" FOREIGN KEY (category) REFERENCES public."Category"(id) ON DELETE CASCADE;


--
-- Name: TournamentResult TournamentResult_loser_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."TournamentResult"
    ADD CONSTRAINT "TournamentResult_loser_fkey" FOREIGN KEY (loser) REFERENCES public."Participant"(id) ON DELETE CASCADE;


--
-- Name: TournamentResult TournamentResult_winner_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."TournamentResult"
    ADD CONSTRAINT "TournamentResult_winner_fkey" FOREIGN KEY (winner) REFERENCES public."Participant"(id) ON DELETE CASCADE;


--
-- Name: TournamentResult TournamentResult_year_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."TournamentResult"
    ADD CONSTRAINT "TournamentResult_year_fkey" FOREIGN KEY (year) REFERENCES public."Year"(year) ON DELETE CASCADE;


--
-- Name: Year Year_iso_code_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Year"
    ADD CONSTRAINT "Year_iso_code_fkey" FOREIGN KEY (iso_code) REFERENCES public."Country"(iso_code) ON DELETE CASCADE;


--
-- Name: Category; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public."Category" ENABLE ROW LEVEL SECURITY;

--
-- Name: Country; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public."Country" ENABLE ROW LEVEL SECURITY;

--
-- Name: Category Enable read access for all users; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Enable read access for all users" ON public."Category" FOR SELECT USING (true);


--
-- Name: Country Enable read access for all users; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Enable read access for all users" ON public."Country" FOR SELECT USING (true);


--
-- Name: Participant Enable read access for all users; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Enable read access for all users" ON public."Participant" FOR SELECT USING (true);


--
-- Name: ParticipantMember Enable read access for all users; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Enable read access for all users" ON public."ParticipantMember" FOR SELECT USING (true);


--
-- Name: RankingResult Enable read access for all users; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Enable read access for all users" ON public."RankingResult" FOR SELECT USING (true);


--
-- Name: Tavily Enable read access for all users; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Enable read access for all users" ON public."Tavily" FOR SELECT USING (true);


--
-- Name: TournamentResult Enable read access for all users; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Enable read access for all users" ON public."TournamentResult" FOR SELECT USING (true);


--
-- Name: Year Enable read access for all users; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Enable read access for all users" ON public."Year" FOR SELECT USING (true);


--
-- Name: Participant; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public."Participant" ENABLE ROW LEVEL SECURITY;

--
-- Name: ParticipantMember; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public."ParticipantMember" ENABLE ROW LEVEL SECURITY;

--
-- Name: RankingResult; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public."RankingResult" ENABLE ROW LEVEL SECURITY;

--
-- Name: Tavily; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public."Tavily" ENABLE ROW LEVEL SECURITY;

--
-- Name: TournamentResult; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public."TournamentResult" ENABLE ROW LEVEL SECURITY;

--
-- Name: Year; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public."Year" ENABLE ROW LEVEL SECURITY;

--
-- PostgreSQL database dump complete
--
